language: python

python:
  - "2.7"
  - "3.3"

env:
  - DJANGO="https://www.djangoproject.com/download/1.7b1/tarball/"

install:
  - pip install $DJANGO
  - pip install -r reqs/dev.txt
  - pip install coverage coveralls
  - export PYTHONPATH=.

script:
  - coverage run --source=apps manage.py test --settings=settings.dev

after_success:
  coveralls